[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
force_sort_within_sections = true
default_section = "THIRDPARTY"
known_first_party = ["app", "core", "infrastructure"]

[tool.ruff]
line-length = 100
target-version = "py310"
fix = true

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "C4"]
ignore = ["E501", "I001"]

[tool.ruff.lint.isort]
known-first-party = ["app", "core", "infrastructure"]
combine-as-imports = true

[tool.pylint.main]
py-version = "3.10"
extension-pkg-allow-list = ["PySide6", "PIL"]

[tool.pylint.typecheck]
generated-members = ["PySide6.*"]

[tool.pylint.design]
max-attributes = 24
min-public-methods = 0
max-locals = 55
max-statements = 140
# Allow Windows API structure naming patterns
good-names = ["Data1", "Data2", "Data3", "Data4", "GUID", "SIZE", "BITMAP", "BITMAPINFO", "BITMAPINFOHEADER"]

[tool.pylint.format]
max-line-length = 100

[tool.pylint.variables]
additional-builtins = ["Data1", "Data2", "Data3", "Data4"]



