// AUTO-GENERATED by scripts/gen_testid_ts.py from qa/web/testid_constants.py — DO NOT EDIT.

export const MAIN_RESULT_TREE = "main-result-tree";
export const MAIN_STATUS_BAR = "main-status-bar";
export const MAIN_STATUS_ERROR = "main-status-error";
export const MAIN_EXECUTE_ERROR = "main-execute-error";
export const MAIN_SCAN_BUTTON = "main-scan-button";
export const MAIN_EXECUTE_BUTTON = "main-execute-button";
export const MAIN_LANG_TOGGLE = "main-lang-toggle";
export const MAIN_SETTINGS_BUTTON = "main-settings-button";
export const MAIN_MANIFEST_INPUT = "main-manifest-input";
export const MAIN_MANIFEST_OPEN = "main-manifest-open-button";
export const MAIN_EMPTY_STATE = "main-empty-state";
export const MAIN_EMPTY_SCAN = "main-empty-scan";
export const MAIN_EMPTY_OPEN = "main-empty-open";
export const MAIN_MENU_BAR = "main-menu-bar";
export const MENU_FILE = "menu-file";
export const MENU_FILE_SCAN = "menu-file-scan";
export const MENU_FILE_OPEN = "menu-file-open";
export const MENU_ACTION = "menu-action";
export const MENU_ACTION_SET = "menu-action-set";
export const MENU_ACTION_EXECUTE = "menu-action-execute";
export const MENU_ACTION_EXECUTE_SELECTED = "menu-action-execute-selected";
export const MENU_LIST = "menu-list";
export const MENU_LIST_REMOVE_FROM_LIST = "menu-list-remove-from-list";
export const MENU_VIEW = "menu-view";
export const MENU_VIEW_LANG_EN = "menu-view-lang-en";
export const MENU_VIEW_LANG_ZH = "menu-view-lang-zh";
export const FS_BROWSER = "fs-browser";
export const FS_BROWSER_UP = "fs-browser-up";
export const FS_BROWSER_PATH = "fs-browser-path";
export const FS_BROWSER_ENTRY = "fs-browser-entry";
export const FS_BROWSER_FILENAME = "fs-browser-filename";
export const FS_BROWSER_CONFIRM = "fs-browser-confirm";
export const FS_BROWSER_CANCEL = "fs-browser-cancel";
export const FS_BROWSER_ERROR = "fs-browser-error";
export const SCAN_ADD_SOURCE = "scan-add-source-button";
export const SCAN_DIALOG = "scan-dialog";
export const SCAN_SOURCE_LIST = "scan-source-list";
export const SCAN_OUTPUT_PATH = "scan-output-path";
export const SCAN_OUTPUT_BROWSE = "scan-output-browse";
export const SCAN_START_BUTTON = "scan-start-button";
export const SCAN_CANCEL_BUTTON = "scan-cancel-button";
export const SCAN_PROGRESS_LOG = "scan-progress-log";
export const SCAN_PROGRESS_BAR = "scan-progress-bar";
export const SCAN_STATUS_TEXT = "scan-status-text";
export const SCAN_THROUGHPUT_TEXT = "scan-throughput-text";
export const SCAN_ETA_TEXT = "scan-eta-text";
export const SCAN_ADVANCED = "scan-advanced";
export const SCAN_AUTO_SELECT = "scan-auto-select";
export const SCAN_AGGRESSIVE_DELETE = "scan-aggressive-delete";
export const SCAN_AUTOTUNE = "scan-autotune";
export const SCAN_PHASH_THRESHOLD = "scan-phash-threshold";
export const SCAN_DHASH_THRESHOLD = "scan-dhash-threshold";
export const SCAN_COLOR_THRESHOLD = "scan-color-threshold";
export const SCAN_RESCAN_CONFIRM_DIALOG = "scan-rescan-confirm-dialog";
export const SCAN_RESCAN_CONFIRM_CANCEL = "scan-rescan-confirm-cancel";
export const SCAN_RESCAN_CONFIRM_DISCARD = "scan-rescan-confirm-discard";
export const EXECUTE_DIALOG = "execute-dialog";
export const EXECUTE_ALL_DELETE_BANNER = "execute-all-delete-banner";
export const EXECUTE_HIDDEN_DESTRUCTIVE_BANNER = "execute-hidden-destructive-banner";
export const EXECUTE_TYPE_FILTER = "execute-type-filter";
export const EXECUTE_TREE = "execute-tree";
export const EXECUTE_BTN_EXECUTE = "execute-btn-execute";
export const EXECUTE_BTN_EXECUTE_SELECTED = "execute-btn-execute-selected";
export const EXECUTE_PREVIEW_PANE = "execute-preview-pane";
export const EXECUTE_PREVIEW_IMAGE = "execute-preview-image";
export const EXECUTE_ALL_DELETE_CONFIRM = "execute-all-delete-confirm";
export const EXECUTE_ALL_DELETE_CONFIRM_YES = "execute-all-delete-confirm-yes";
export const EXECUTE_ALL_DELETE_CONFIRM_NO = "execute-all-delete-confirm-no";
export const EXECUTE_REMOVE_CONFIRM = "execute-remove-confirm";
export const EXECUTE_REMOVE_CONFIRM_YES = "execute-remove-confirm-yes";
export const EXECUTE_REMOVE_CONFIRM_NO = "execute-remove-confirm-no";
export const EXECUTE_RESULT_MISSING = "execute-result-missing";
export const EXECUTE_RESULT_FAILED = "execute-result-failed";
export const LOCK_CONFIRM_DIALOG = "lock-confirm-dialog";
export const LOCK_CONFIRM_BTN_UNLOCK_APPLY = "lock-confirm-btn-unlock-apply";
export const LOCK_CONFIRM_BTN_UNLOCKED_ONLY = "lock-confirm-btn-unlocked-only";
export const LOCK_CONFIRM_BTN_CANCEL = "lock-confirm-btn-cancel";
export const DELETE_CONFIRM_DIALOG = "delete-confirm-dialog";
export const DELETE_CONFIRM_BTN_CONFIRM = "delete-confirm-btn-confirm";
export const DELETE_CONFIRM_BTN_CANCEL = "delete-confirm-btn-cancel";
export const PRUNE_CONFIRM_DIALOG = "prune-confirm-dialog";
export const PRUNE_BTN_REMOVE = "prune-btn-remove";
export const PRUNE_BTN_KEEP = "prune-btn-keep";
export const PRUNE_INCLUDE_ACTIONED = "prune-include-actioned";
export const PRUNE_REMEMBER = "prune-remember";
export const PREVIEW_PANE = "preview-pane";
export const PREVIEW_SINGLE_IMAGE = "preview-single-image";
export const PREVIEW_INFO = "preview-info";
export const PREVIEW_RESIZE_HANDLE = "preview-resize-handle";
export const FULLRES_DIALOG = "fullres-dialog";
export const FULLRES_IMAGE = "fullres-image";
export const CONTEXT_MENU = "context-menu";
export const CTX_SET_ACTION_KEEP = "ctx-set-action-keep";
export const CTX_SET_ACTION_DELETE = "ctx-set-action-delete";
export const CTX_SET_ACTION_REMOVE = "ctx-set-action-remove";
export const CTX_OPEN_FOLDER = "ctx-open-folder";
export const CTX_LOCK = "ctx-lock";
export const CTX_UNLOCK = "ctx-unlock";
export const CTX_APPLY_BEST_COPY = "ctx-apply-best-copy";
export const CTX_SET_ACTION_BY_FIELD = "ctx-set-action-by-field";
export const CTX_EXECUTE_SELECTED = "ctx-execute-selected";
export const ACTION_MAIN_BUTTON = "main-action-button";
export const ACTION_DIALOG = "action-dialog";
export const ACTION_FIELD_COMBO = "action-field-combo";
export const ACTION_SIMPLE_ROW = "action-simple-row";
export const ACTION_SIMPLE_OP = "action-simple-op";
export const ACTION_SIMPLE_TEXT = "action-simple-text";
export const ACTION_SIMPLE_DISABLED_NOTE = "action-simple-disabled-note";
export const ACTION_REGEX_ROW = "action-regex-row";
export const ACTION_REGEX_INPUT = "action-regex-input";
export const ACTION_VALIDATION_ICON = "action-validation-icon";
export const ACTION_VALIDATION_ERROR = "action-validation-error";
export const ACTION_NUMERIC_ROW = "action-numeric-row";
export const ACTION_NUMERIC_MODE_THRESHOLD = "action-numeric-mode-threshold";
export const ACTION_NUMERIC_MODE_TOPN = "action-numeric-mode-topn";
export const ACTION_NUMERIC_CMP = "action-numeric-cmp";
export const ACTION_NUMERIC_VALUE = "action-numeric-value";
export const ACTION_NUMERIC_ERROR = "action-numeric-error";
export const ACTION_NUMERIC_ORDER = "action-numeric-order";
export const ACTION_NUMERIC_N = "action-numeric-n";
export const ACTION_MATCH_COUNTER = "action-match-counter";
export const ACTION_ACTION_COMBO = "action-action-combo";
export const ACTION_BTN_APPLY = "action-btn-apply";
export const ACTION_PREVIEW_LIST = "action-preview-list";
export const ACTION_PREVIEW_TRUNCATED = "action-preview-truncated";
export const ACTION_LOCK_CONFIRM_DIALOG = "action-lock-confirm-dialog";
export const ACTION_LOCK_CONFIRM_BTN_UNLOCK_APPLY = "action-lock-confirm-btn-unlock-apply";
export const ACTION_LOCK_CONFIRM_BTN_UNLOCKED_ONLY = "action-lock-confirm-btn-unlocked-only";
export const ACTION_LOCK_CONFIRM_BTN_CANCEL = "action-lock-confirm-btn-cancel";
export const ACTION_RECENT_SELECT = "action-recent-select";
export const ACTION_RECENT_CLEAR = "action-recent-clear";
export const ACTION_DELETE_CONFIRM_SUMMARY = "action-delete-confirm-summary";
export const DLGE_SETTINGS_DIALOG = "settings-dialog";
export const DLGE_SETTINGS_SAVE = "settings-save-button";
export const DLGE_SETTINGS_CANCEL = "settings-cancel-button";
export const DLGE_SETTINGS_PRUNE_SELECT = "settings-prune-select";
export const DLGE_CONFIRM_CANCEL = "confirm-cancel-button";
export const GRID_CONTAINER = "grid-container";
export const GMC_BAR = "gmc-bar";
export const GMC_PLAY_PAUSE = "gmc-play-pause";
export const GMC_PROGRESS_SLIDER = "gmc-progress-slider";
export const GMC_CURRENT_TIME = "gmc-current-time";
export const GMC_DURATION = "gmc-duration";
export const GMC_MUTE_BUTTON = "gmc-mute-button";
export const GMC_VOLUME_SLIDER = "gmc-volume-slider";

export function rowFileTestid(groupId: string, basename: string): string {
  return `row-file-${groupId}-${basename}`;
}

export function rowGroupTestid(groupId: string): string {
  return `row-group-${groupId}`;
}

export function rowDecisionTestid(groupId: string, basename: string): string {
  return `row-decision-${groupId}-${basename}`;
}

export function rowDecisionOptionTestid(groupId: string, basename: string, option: string): string {
  return `row-decision-${groupId}-${basename}-${option}`;
}

export function rowLockTestid(groupId: string, basename: string): string {
  return `row-lock-${groupId}-${basename}`;
}

export function executeAllDeleteJumpTestid(groupId: string): string {
  return `execute-all-delete-jump-${groupId}`;
}

export function scanSourceLabelTestid(idx: number): string {
  return `scan-source-${idx}-label`;
}

export function scanSourcePathTestid(idx: number): string {
  return `scan-source-${idx}-path`;
}

export function scanSourceRecursiveTestid(idx: number): string {
  return `scan-source-${idx}-recursive`;
}

export function scanSourceBrowseTestid(idx: number): string {
  return `scan-source-${idx}-browse`;
}

export function executeRowTestid(groupId: string, basename: string): string {
  return `execute-row-${groupId}-${basename}`;
}

export function actionCheatsheetTestid(token: string): string {
  return `action-cheatsheet-${token}`;
}

export function colHeaderTestid(colId: string): string {
  return `col-header-${colId}`;
}

export function colResizeTestid(colId: string): string {
  return `col-resize-${colId}`;
}

export function gridVideoTileTestid(groupId: string, basename: string): string {
  return `grid-video-tile-${groupId}-${basename}`;
}

export function gridImageTileTestid(groupId: string, basename: string): string {
  return `grid-image-tile-${groupId}-${basename}`;
}
