// AUTO-GENERATED by scripts/gen_testid_ts.py from qa/web/testid_constants.py — DO NOT EDIT.

export const MAIN_RESULT_TREE = "main-result-tree";
export const MAIN_STATUS_BAR = "main-status-bar";
export const MAIN_SCAN_BUTTON = "main-scan-button";
export const MAIN_EXECUTE_BUTTON = "main-execute-button";
export const MAIN_LANG_TOGGLE = "main-lang-toggle";
export const MAIN_SETTINGS_BUTTON = "main-settings-button";
export const MAIN_MANIFEST_INPUT = "main-manifest-input";
export const MAIN_MANIFEST_OPEN = "main-manifest-open-button";
export const SCAN_ADD_SOURCE = "scan-add-source-button";
export const SCAN_DIALOG = "scan-dialog";
export const SCAN_SOURCE_LIST = "scan-source-list";
export const SCAN_OUTPUT_PATH = "scan-output-path";
export const SCAN_START_BUTTON = "scan-start-button";
export const SCAN_CANCEL_BUTTON = "scan-cancel-button";
export const SCAN_PROGRESS_LOG = "scan-progress-log";
export const SCAN_PROGRESS_BAR = "scan-progress-bar";
export const SCAN_STATUS_TEXT = "scan-status-text";
export const EXEC_DIALOG = "exec-dialog";
export const EXEC_ACTION_SELECT = "exec-action-select";
export const EXEC_REGEX_INPUT = "exec-regex-input";
export const EXEC_PREVIEW_TABLE = "exec-preview-table";
export const EXEC_CONFIRM_BUTTON = "exec-confirm-button";
export const EXEC_CANCEL_BUTTON = "exec-cancel-button";
export const DLGE_SETTINGS_DIALOG = "settings-dialog";
export const DLGE_SETTINGS_SAVE = "settings-save-button";
export const DLGE_SETTINGS_CANCEL = "settings-cancel-button";
export const DLGE_CONFIRM_OK = "confirm-ok-button";
export const DLGE_CONFIRM_CANCEL = "confirm-cancel-button";

export function rowFileTestid(groupId: string, basename: string): string {
  return `row-file-${groupId}-${basename}`;
}

export function rowGroupTestid(groupId: string): string {
  return `row-group-${groupId}`;
}

export function rowDecisionTestid(groupId: string, basename: string): string {
  return `row-decision-${groupId}-${basename}`;
}

export function rowLockTestid(groupId: string, basename: string): string {
  return `row-lock-${groupId}-${basename}`;
}
