"""Generate frontend/src/testids.ts from qa/web/testid_constants.py.

Usage
-----
python scripts/gen_testid_ts.py               # writes frontend/src/testids.ts
python scripts/gen_testid_ts.py --out -       # writes to stdout
python scripts/gen_testid_ts.py --out <path>  # writes to given path

The --check flag is accepted as a no-op alias for backwards compat with
scripts that used an earlier interface; use check_testid_parity.py instead.
"""
from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

# Repo root is one level up from this script.
_REPO = Path(__file__).resolve().parent.parent


def render_testids_ts() -> str:
    """Return the full text of testids.ts generated from testid_constants.py.

    This is the single source of truth for the rendering logic; both
    gen_testid_ts.py (write) and check_testid_parity.py (verify) call it.
    """
    # Ensure the repo root is on sys.path so the qa package is importable.
    repo_str = str(_REPO)
    if repo_str not in sys.path:
        sys.path.insert(0, repo_str)

    mod = importlib.import_module("qa.web.testid_constants")

    lines: list[str] = [
        "// AUTO-GENERATED by scripts/gen_testid_ts.py from qa/web/testid_constants.py"
        " — DO NOT EDIT.",
        "",
    ]

    for name, value in vars(mod).items():
        # Emit only UPPERCASE names whose value is a plain string.
        if name.isupper() and isinstance(value, str):
            lines.append(f'export const {name} = "{value}";')

    # Append the two row-helper functions (hand-templated; camelCase names).
    lines.append("")
    lines.append(
        "export function rowFileTestid(groupId: string, basename: string): string {"
    )
    lines.append("  return `row-file-${groupId}-${basename}`;")
    lines.append("}")
    lines.append("")
    lines.append("export function rowGroupTestid(groupId: string): string {")
    lines.append("  return `row-group-${groupId}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function rowDecisionTestid(groupId: string, basename: string): string {"
    )
    lines.append("  return `row-decision-${groupId}-${basename}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function rowDecisionOptionTestid(groupId: string, basename: string, option: string): string {"
    )
    lines.append("  return `row-decision-${groupId}-${basename}-${option}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function rowLockTestid(groupId: string, basename: string): string {"
    )
    lines.append("  return `row-lock-${groupId}-${basename}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function executeAllDeleteJumpTestid(groupId: string): string {"
    )
    lines.append("  return `execute-all-delete-jump-${groupId}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function scanSourceLabelTestid(idx: number): string {"
    )
    lines.append("  return `scan-source-${idx}-label`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function scanSourcePathTestid(idx: number): string {"
    )
    lines.append("  return `scan-source-${idx}-path`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function scanSourceRecursiveTestid(idx: number): string {"
    )
    lines.append("  return `scan-source-${idx}-recursive`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function scanSourceBrowseTestid(idx: number): string {"
    )
    lines.append("  return `scan-source-${idx}-browse`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function executeRowTestid(groupId: string, basename: string): string {"
    )
    lines.append("  return `execute-row-${groupId}-${basename}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function actionCheatsheetTestid(token: string): string {"
    )
    lines.append("  return `action-cheatsheet-${token}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function colHeaderTestid(colId: string): string {"
    )
    lines.append("  return `col-header-${colId}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function colResizeTestid(colId: string): string {"
    )
    lines.append("  return `col-resize-${colId}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function gridVideoTileTestid(groupId: string, basename: string): string {"
    )
    lines.append("  return `grid-video-tile-${groupId}-${basename}`;")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function gridImageTileTestid(groupId: string, basename: string): string {"
    )
    lines.append("  return `grid-image-tile-${groupId}-${basename}`;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=None,
        help="Output path. Use '-' for stdout. Defaults to frontend/src/testids.ts.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="No-op; use check_testid_parity.py for parity checking.",
    )
    args = parser.parse_args(argv)

    content = render_testids_ts()

    if args.out == "-":
        sys.stdout.write(content)
        return 0

    out_path = Path(args.out) if args.out else _REPO / "frontend" / "src" / "testids.ts"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path.relative_to(_REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
